package digest

import (
	"bytes"
	"fmt"
	htmltmpl "html/template"
	texttmpl "text/template"
)

// RenderMarkdown renders the digest to Markdown (used for files and chat
// webhooks).
func (d Digest) RenderMarkdown() (string, error) {
	var buf bytes.Buffer
	if err := markdownTmpl.Execute(&buf, d); err != nil {
		return "", fmt.Errorf("render markdown: %w", err)
	}
	return buf.String(), nil
}

// RenderHTML renders the digest to a self-contained HTML document with inline
// CSS (email-client friendly).
func (d Digest) RenderHTML() (string, error) {
	var buf bytes.Buffer
	if err := htmlTmpl.Execute(&buf, d); err != nil {
		return "", fmt.Errorf("render html: %w", err)
	}
	return buf.String(), nil
}

var markdownTmpl = texttmpl.Must(texttmpl.New("md").Parse(`# {{ .Title }}

_{{ .Date.Format "Monday, 2 January 2006" }}_

{{ if .Intro }}{{ .Intro }}

{{ end }}{{ range .Sections }}## {{ .Title }}

{{ range .Items }}- **{{ if .URL }}[{{ .Headline }}]({{ .URL }}){{ else }}{{ .Headline }}{{ end }}**{{ if .Source }} — {{ .Source }}{{ end }}{{ if .Summary }}
  {{ .Summary }}{{ end }}
{{ end }}
{{ end }}`))

var htmlTmpl = htmltmpl.Must(htmltmpl.New("html").Parse(`<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{{ .Title }}</title>
</head>
<body style="margin:0;padding:0;background:#f4f1ea;">
<table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="background:#f4f1ea;">
<tr><td align="center" style="padding:32px 16px;">
<table role="presentation" width="600" cellpadding="0" cellspacing="0" style="max-width:600px;width:100%;background:#ffffff;border-radius:10px;overflow:hidden;font-family:-apple-system,Segoe UI,Roboto,Helvetica,Arial,sans-serif;color:#1a1a1a;">
<tr><td style="padding:28px 32px 8px 32px;">
<h1 style="margin:0;font-size:24px;line-height:1.2;color:#111;">{{ .Title }}</h1>
<div style="margin-top:4px;font-size:13px;color:#8a8577;">{{ .Date.Format "Monday, 2 January 2006" }}</div>
</td></tr>
{{ if .Intro }}<tr><td style="padding:12px 32px 4px 32px;font-size:16px;line-height:1.55;color:#33312c;">{{ .Intro }}</td></tr>{{ end }}
{{ range .Sections }}
<tr><td style="padding:24px 32px 0 32px;">
<h2 style="margin:0 0 8px 0;font-size:13px;letter-spacing:.08em;text-transform:uppercase;color:#c05621;">{{ .Title }}</h2>
</td></tr>
{{ range .Items }}
<tr><td style="padding:8px 32px;">
{{ if .URL }}<a href="{{ .URL }}" style="font-size:17px;font-weight:600;color:#1a1a1a;text-decoration:none;">{{ .Headline }}</a>{{ else }}<span style="font-size:17px;font-weight:600;color:#1a1a1a;">{{ .Headline }}</span>{{ end }}
{{ if .Source }}<span style="font-size:12px;color:#8a8577;"> · {{ .Source }}</span>{{ end }}
{{ if .Summary }}<div style="margin-top:4px;font-size:15px;line-height:1.5;color:#4a463f;">{{ .Summary }}</div>{{ end }}
</td></tr>
{{ end }}
{{ end }}
<tr><td style="padding:28px 32px;border-top:1px solid #eee;font-size:12px;color:#b0aaa0;">Generated by dev-digest</td></tr>
</table>
</td></tr>
</table>
</body>
</html>`))
